web/src/views/cars.py
import json
from datetime import date, timedelta
from producers import produce_data, produce_dmz
from utils.dueshit import get_car_maintenance_stuff
from flask import Blueprint, request, render_template, url_for, redirect, flash, session
blueprint = Blueprint('cars', __name__, url_prefix='/cars')


@blueprint.route('/')
def list_cars():
    """
    Display cars list emplate.
    """
    if not session.get('token'):
        return 'Not authed.'

    response = produce_data({
        'action': 'get_cars',
        'token': session.get('token')
    })

    if not response:
        return 'Data was not returned in time.'

    cars = response.get('cars')
    if cars is None:
        cars = []

    return render_template('cars/list.html', cars=cars)


@blueprint.route('/<int:id>')
def display_car(id):
    """
    Display individual car display template.
    """
    if not session.get('token'):
        return 'Not authed.'

    response = produce_data({
        'action': 'get_car',
        'id': id,
        'token': session.get('token')
    })

    if not response:
        return 'Data was not returned in time.'

    return render_template('cars/display.html', car=response.get('car'))


@blueprint.route('/<int:id>/delete', methods=['POST'])
def delete_car(id):
    """
    Delete car from database.
    """
    if not session.get('token'):
        return 'Not authed.'

    response = produce_data({
        'action': 'delete_car',
        'id': id,
        'token': session.get('token')
    })

    if not response:
        return 'Data was not returned in time.'

    if response and response['success'] == True:
        flash('Your car has been deleted!')
    else:
        flash('Your car has NOT been deleted!')

    return redirect(url_for('cars.list_cars'))


@blueprint.route('/<int:id>/update', methods=['POST'])
def update_car(id):
    """
    Update car mileage.
    """
    if not session.get('token'):
        return 'Not authed.'

    response = produce_data({
        'action': 'update_car',
        'id': id,
        'mileage': request.form.get('mileage'),
        'weekly_mileage': request.form.get('weekly_mileage'),
        'token': session.get('token')
    })

    if not response:
        return 'Data was not returned in time.'

    if response and response['success'] == True:
        flash('Your car mileage has been updated!')
    else:
        flash('Your car mileage has NOT been updated!')

    return redirect(url_for('cars.display_car', id=id))


@blueprint.route('/add')
def add_car():
    """
    Display car creation template.
    """
    return render_template('cars/create.html')


@blueprint.route('/add', methods=['POST'])
def add_car_post():
    """
    Process register request.
    """
    make = request.form.get("make")
    model = request.form.get("model")
    year = request.form.get("year")
    mileage = request.form.get("mileage")
    weekly_mileage = request.form.get("weekly_mileage")
    error = None

    if not make:
        error = 'Invalid make.'

    if not model:
        error = 'Invalid model.'

    if not year:
        error = 'Invalid year.'

    response = None
    if not error:
        response = produce_data({
            'action': 'add_car',
            'token': session.get('token'),
            'make': make,
            'model': model,
            'year': year,
            'mileage': mileage,
            'weekly_mileage': weekly_mileage
        })

    if response and response['success'] == True:
        flash('Your car has been added!')
        return redirect(url_for('cars.list_cars'))
    else:
        flash('Your car has NOT been added!')


    return render_template('cars/create.html', error=error)


@blueprint.route('/<int:id>/recalls')
def car_recalls(id):
    """
    Display individual car recalls.
    """
    if not session.get('token'):
        return 'Not authed.'

    db_response = produce_data({
        'action': 'get_car',
        'id': id,
        'token': session.get('token')
    })

    car = db_response.get('car')
    if not car:
        return 'Car does not exist!'

    dmz_response = produce_dmz({
        'action': 'get_recalls',
        'make': car.get('make'),
        'model': car.get('model'),
        'year': car.get('year'),
        'mileage': car.get('mileage'),
        'token': session.get('token')
    })

    results = dmz_response.get('results')

    data = results.get('data')
    if data is None:
        data = []
    return render_template(f'cars/display_recalls.html', car=car, data=data)


@blueprint.route('/<int:id>/maintenance')
def car_maintenance(id):
    """
    Display individual car maintenance.
    """
    if not session.get('token'):
        return 'Not authed.'

    db_response = produce_data({
        'action': 'get_car',
        'id': id,
        'token': session.get('token')
    })

    car = db_response.get('car')
    if not car:
        return 'Car does not exist!'

    data = get_car_maintenance_stuff(car)
    return render_template(f'cars/display_maintenance.html', car=car, data=data)


@blueprint.route('/<int:id>/maintenance', methods=['POST'])
def car_maintenance_post(id):
    """
    Get YouTube video.
    """
    if not session.get('token'):
        return 'Not authed.'

    db_response = produce_data({
        'action': 'get_car',
        'id': id,
        'token': session.get('token')
    })

    car = db_response.get('car')
    if not car:
        return 'Car does not exist!'

    query = request.form.get('query')
    year = car.get('year')
    make = car.get('make')
    model = car.get('model')
    full_query = f'{year} {make} {model} {query}'
    dmz_response = produce_dmz({
        'action': 'youtube_search',
        'query': full_query,
        'token': session.get('token')
    })

    if not dmz_response:
        ez_log('LOG', 'NO_DMZ_RESPONSE_YOUTUBE_SEARCH', full_query)
        return 'No response from DMZ!'

    video_id = None
    try:
        video_id = dmz_response['results'][0]['id']['videoId']
    except:
        return 'No video found!'

    return render_template(
        'cars/display_video.html', car=car, query=query, video_id=video_id
    )


@blueprint.route('/<int:id>/video-playlist')
def video_playlist(id):
    """
    Get YouTube video playlist.
    """
    if not session.get('token'):
        return 'Not authed.'

    db_response = produce_data({
        'action': 'get_car',
        'id': id,
        'token': session.get('token')
    })

    car = db_response.get('car')
    if not car:
        return 'Car does not exist!'

    query = request.form.get('query')
    year = car.get('year')
    make = car.get('make')
    model = car.get('model')
    full_query = f'{year} {make} {model} {query}'
    dmz_response = produce_dmz({
        'action': 'youtube_search',
        'query': full_query,
        'token': session.get('token')
    })

    if not dmz_response:
        ez_log('LOG', 'NO_DMZ_RESPONSE_YOUTUBE_SEARCH', full_query)
        return 'No response from DMZ!'

    videos = []
    for video in dmz_response.get('results', []):
        try:
            videos.append(video['id']['videoId'])
        except:
            pass

    return render_template(
        'cars/display_videos.html', car=car, videos=videos
    )


@blueprint.route('/<int:id>/add-events')
def add_events_to_calendar(id):
    """
    Add events to google calendar.
    """
    if not session.get('token'):
        return 'Not authed.'

    db_response = produce_data({
        'action': 'get_car',
        'id': id,
        'token': session.get('token')
    })

    car = db_response.get('car')
    if not car:
        return 'Car does not exist!'

    dmz_response = produce_dmz({
        'action': 'get_oauth_link'
    })

    if not dmz_response:
        ez_log('LOG', 'NO_DMZ_RESPONSE_ADD_EVENTS', '...')
        return 'No response from DMZ!'

    return render_template(
        'cars/display_add_events.html', car=car, oauth_link=dmz_response.get('results')
    )


@blueprint.route('/<int:id>/add-events', methods=['POST'])
def add_events_to_calendar_post(id):
    """
    Add events to google calendar.
    """
    if not session.get('token'):
        return 'Not authed.'

    db_response = produce_data({
        'action': 'get_car',
        'id': id,
        'token': session.get('token')
    })

    if not response:
        return 'Data was not returned in time.'

    car = db_response.get('car')
    if not car:
        return 'Car does not exist!'

    data = get_car_maintenance_stuff(car)

    if data is None:
        return 'No data received!'

    events = []
    year = car.get('year')
    make = car.get('make')
    model = car.get('model')

    for event in data:
        d = date.strftime(date.today() + timedelta(days=event.get('due_in_days', 0)), '%Y-%m-%d')
        desc = event.get('desc')
        events.append({
            'summary': f'{year} {make} {model}: {desc}',
            'date': d
        })

    dmz_response = produce_dmz({
        'action': 'add_events',
        'oauth_code': request.form.get('oauth_code'),
        'events': events,
    })

    if dmz_response and dmz_response['success'] == True:
        flash('Events have been added to your calendar!')
    else:
        flash('Events have NOT been added to your calendar.')

    return render_template(
        'cars/display_add_events.html',
        car=car, results=dmz_response.get('results')
    )

web/src/templates/cars/create.html
{% extends 'base.html' %}

{% block title %}Add Car{% endblock %}

{% block content %}

{% if error %}
  <p>{{ error }}</p>
{% endif %}

<form method="POST">
  <div class="form-group">
    <label>Make</label>
    <input class="form-control" type="text" name="make" required />
  </div>

  <div class="form-group">
    <label>Model</label>
    <input class="form-control" type="text" name="model" required />
  </div>

  <div class="form-group">
    <label>Year</label>
    <input class="form-control" type="number" name="year" required />
  </div>

  <div class="form-group">
    <label>Mileage</label>
    <input class="form-control" type="number" name="mileage" required />
  </div>

  <div class="form-group">
    <label>How many miles do you drive per week?</label>
    <input class="form-control" type="number" name="weekly_mileage" value="250" required />
  </div>

  <button type="submit" class="btn btn-primary">Add Car</button>
</form>
{% endblock %}

web/src/templates/cars/display.html
{% extends 'base.html' %}

{% block title %}View Car{% endblock %}

{% block content %}

<div class="btn-group">
  <a href="{{ url_for('cars.car_recalls', id=car.id) }}" class="btn btn-warning">
    View Recalls
  </a>
  <a href="{{ url_for('cars.car_maintenance', id=car.id) }}" class="btn btn-secondary">
    View Maintenance
  </a>
  <a href="{{ url_for('cars.add_events_to_calendar', id=car.id) }}" class="btn btn-success">
    Add Maintenance Events to Google Calendar
  </a>
  <a href="{{ url_for('cars.video_playlist', id=car.id) }}" class="btn btn-danger">
    Video Playlist
  </a>
</div>

<form style="float:right" action="{{ url_for('cars.delete_car', id=car.id) }}" method="POST">
  <button class="btn btn-danger" type="submit">Delete Car</button>
</form>

<br/><br/>
<h1>
  <a href="{{ url_for('cars.display_car', id=car.id) }}">
    {{ car.year }} {{ car.make }} {{ car.model }}
  </a>
  <small>({{ car.mileage }} miles)</small>
</h1>

{% block inner_content %}

<form action="{{ url_for('cars.update_car', id=car.id) }}" method="POST">
  <div class="alert alert-danger" role="alert">
    Your car may have recalls! Check the 'View Recalls' tab!
  </div>

  <div class="form-group">
    <label>Total Mileage</label>
    <input class="form-control" type="number" name="mileage" value="{{ car.mileage }}" required />
  </div>

  <div class="form-group">
    <label>How many miles do you drive per week?</label>
    <input class="form-control" type="number" name="weekly_mileage" value="{{ car.weekly_mileage }}" required />
  </div>

  <button class="btn btn-success" type="submit">Update Mileage</button>
</form>
{% endblock %}

{% endblock %}

web/src/templates/cars/display_add_events.html
{% extends 'cars/display.html' %}


{% block inner_content %}
<a class="btn btn-warning" target="_blank" href="{{ oauth_link }}">
  Get OAuth Access Code to your Google Account
</a>

<br/>
<br/>

<form method="POST">
  <div class="form-group">
    <label>OAuth Code</label>
    <input class="form-control" type="text" name="oauth_code" required />
  </div>

  <input class="btn btn-primary" type="submit" value="Add Events" />
</form>

<p>
{% if results %}
  {% for result in results %}
    <a href="{{ result }}">{{ result }}</a><br/>
  {% endfor %}
{% endif %}
</p>

{% endblock %}

web/src/templates/cars/display_maintenance.html
{% extends 'cars/display.html' %}


{% block inner_content %}
<table class="table">
  <thead>
    <th>Description</th>
    <th>Due Every X Miles</th>
    <th>Due in X Miles</th>
    <th>Due in X Days</th>
    <th>Hours</th>
    <th>Difficulty</th>
    <th></th>
  </thead>

  <tbody>
    {% for maint in data %}
      {% if maint.due_in_miles > 0 %}
      <tr>
        <td>{{ maint.desc }}</td>
        <td>{{ maint.due_mileage }} miles</td>
        <td>{{ maint.due_in_miles }} miles</td>
        <td>{{ maint.due_in_days }} days</td>
        <td>{{ maint.repair.repair_hours }}</td>
        <td>{{ maint.repair.repair_difficulty }}</td>
        <td>
          <form method="POST">
            <input name="query" value="{{ maint.desc }}" type="hidden" />
            <button class="btn btn-primary" type="submit">Find Video</button>
          </form>
        </td>
      </tr>
      {% endif %}
    {% endfor %}
  </tbody>
</table>
{% endblock %}

web/src/templates/cars/display_recalls.html
{% extends 'cars/display.html' %}


{% block inner_content %}
<table class="table">
  <thead>
    <th>Description</th>
    <th>Corrective Action</th>
    <th>Recall Number</th>
    <th>Recall Date</th>
  </thead>

  <tbody>
    {% for recall in data %}
      <tr>
        <td>{{ recall.desc }}</td>
        <td>{{ recall.corrective_action }}</td>
        <td>{{ recall.recall_number }}</td>
        <td>{{ recall.recall_date }}</td>
      </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock %}

web/src/templates/cars/display_video.html
{% extends 'cars/display.html' %}


{% block inner_content %}
<p>"{{ query }}"</p>
<iframe width="560" height="315" src="https://www.youtube.com/embed/{{ video_id }}" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
{% endblock %}

web/src/templates/cars/display_videos.html
{% extends 'cars/display.html' %}


{% block inner_content %}
{% for video_id in videos %}
  <iframe width="560" height="315" src="https://www.youtube.com/embed/{{ video_id }}" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
{% endfor %}
{% endblock %}

web/src/templates/cars/list.html
{% extends 'base.html' %}

{% block title %}Cars{% endblock %}

{% block content %}
<a class="btn btn-primary" href="{{ url_for('cars.add_car') }}">Add Car</a>
<br/><br/>

<table class="table">
  <thead>
    <th>Make</th>
    <th>Model</th>
    <th>Year</th>
    <th>Mileage</th>
  </thead>

  <tbody>
    {% for car in cars %}
      {% include 'cars/list_item.html' %}
    {% endfor %}
  </tbody>
</table>

{% endblock %}

web/src/templates/cars/list_item.html
<tr>
  <td>
    <a href="{{ url_for('cars.display_car', id=car.id) }}">{{ car.make }}</a>
  </td>
  <td>{{ car.model }}</td>
  <td>{{ car.year }}</td>
  <td>{{ car.mileage }}</td>
</tr>